"""empty message

Revision ID: b58727fe1cef
Revises: 24a66bd93c0d
Create Date: 2022-12-04 11:43:06.605737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58727fe1cef'
down_revision = '24a66bd93c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(precision=2),
    #            existing_nullable=False)
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
